# fly.toml app configuration file generated for hangman-broken-firefly-3692 on 2024-06-27T18:45:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hangman-broken-firefly-3692'
primary_region = 'sjc'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
